# Generated by Django 3.1.7 on 2023-11-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidid', models.AutoField(db_column='bidID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'Bid',
                'managed': False,
            },
        ),
    ]
