# Generated by Django 4.2.6 on 2023-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("projectID", models.IntegerField(primary_key=True, serialize=False)),
                ("freelancerID", models.IntegerField(blank=True, null=True)),
                ("bidderID", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=9, null=True)),
                ("description", models.CharField(blank=True, max_length=9, null=True)),
                ("budget", models.IntegerField(blank=True, null=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("categoryID", models.IntegerField(blank=True, null=True)),
                (
                    "projectStatus",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("startDate", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Project",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("userID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=9, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=9, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=9, null=True)),
                ("rating", models.CharField(blank=True, max_length=9, null=True)),
                ("lastLogin", models.TimeField(blank=True, null=True)),
                ("registrationDate", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "UserInfo",
            },
        ),
    ]
