# Generated by Django 4.2.6 on 2023-10-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userInfo", "0002_alter_project_budget_alter_project_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="budget",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="projectID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="projectStatus",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="startDate",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="lastLogin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="rating",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="specialization",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="type",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="userID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
