# Generated by Django 3.1.7 on 2023-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0003_alter_project_budget_alter_project_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
