# Generated by Django 3.1.7 on 2023-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('disputeID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('payment_issues', 'Payment Issues'), ('non-payment', 'Non-Payment'), ('service_issues', 'Service Issues'), ('non-performance', 'Non-Performance'), ('fraud', 'Fraud')], max_length=20, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('disputeStatus', models.CharField(blank=True, choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('awaiting_bids', 'Awaiting Bids')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'Dispute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('budget', models.PositiveIntegerField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('projectStatus', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('awaiting_bids', 'Awaiting Bids')], max_length=15, null=True)),
                ('startDate', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], max_length=10)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': False,
            },
        ),
    ]
