# Generated by Django 3.1.7 on 2023-11-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHome', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
