# Generated by Django 3.1.7 on 2023-11-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidid', models.AutoField(db_column='bidID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'Bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileid', models.AutoField(db_column='profileID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=20, null=True)),
                ('profiletype', models.CharField(blank=True, db_column='profileType', max_length=6, null=True)),
                ('profilepicture', models.CharField(blank=True, db_column='profilePicture', max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(db_column='projectID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('projectstatus', models.CharField(blank=True, db_column='projectStatus', max_length=15, null=True)),
                ('startdate', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('photo', models.CharField(blank=True, max_length=75, null=True)),
            ],
            options={
                'db_table': 'Project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('registrationdate', models.DateTimeField(blank=True, db_column='registrationDate', null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'UserInfo',
                'managed': False,
            },
        ),
    ]
